let shopItemsData = [
    {
      id: "jfhgbvnscs",
      name: "Cotton Velvet",
      price: 24.99,
      desc: "Dreamy and energetic design, suitable for a soft and styled class. ",
      img: "images/aodai11.jpeg",
    },
    {
      id: "ioytrhndcv",
      name: "Cotton Teal",
      price: 26.99,
      desc: "Our newest design with a very traditional and elegant touch. ",
      img: "images/aodai15.jpeg",
    },
    {
      id: "wuefbncxbsn",
      name: "Cotton Black",
      price: 19.99,
      desc: "A product which fits everyone's budget but still highly quality.",
      img: "images/aodai12.jpeg",
    },
    {
      id: "thyfhcbcv",
      name: "Modernized Pattern",
      price: 29.99,
      desc: "A high-quality product with the finest material and design.",
      img: "images/aodai5.jpeg",
    },
    {
      id: "jfhgabvsscs",
      name: "Modernized Sunflower",
      price: 34.99,
      desc: "A design with bold energetic personality and modern style.",
      img: "images/aodai16.jpeg",
    },
    {
      id: "ioytrhnwedcv",
      name: "Lotus Teal",
      price: 39.99,
      desc: "A design that is both elegant and exudes the beauty of the youth.",
      img: "images/aodai17.jpeg",
    },
    {
      id: "wuefbnwqrcxbsn",
      name: "Simple Black",
      price: 22.99,
      desc: "A design that is both simple but still surprisingly unique in a way.",
      img: "images/aodai18.jpg",
    },
    {
      id: "thyfhqwrcbcv",
      name: "Pastel Pink",
      price: 29.99,
      desc: "A design which is created to excessively enhance your beauty.",
      img: "images/aodai19.jpeg",
    },
    {
      id: "jfhgabqwvsscs",
      name: "White Rose",
      price: 32.99,
      desc: "A design with bold energetic personality and modern style.",
      img: "images/aodai20.jpeg",
    },
    {
      id: "ioytrhrwnwedcv",
      name: "Sunny Cotton",
      price: 29.99,
      desc: "A design that is both elegant and exudes the beauty of the youth.",
      img: "images/aodai22.jpeg",
    },
    {
      id: "wuefbnewwqrcxbsn",
      name: "Modernized Kaiju",
      price: 44.99,
      desc: "A design that is both simple but still surprisingly unique in a way.",
      img: "images/aodai21.jpeg",
    },
    {
      id: "thyfhqtrwrcbcv",
      name: "Natural Green",
      price: 29.99,
      desc: "A design which is created to excessively enhance your beauty.",
      img: "images/aodai23.jpeg",
    },
  ];